### ISSUE TITLE
Can't run local instance of ddd-forum due to mysql authentication error

### ISSUE THREAD

**Issue by aashir-khan** [stemmlerjs/ddd-forum#41]
Hi,

I cloned the repo and followed the setup instructions to copy the env template file to .env which I did. The contents of my .env file are:

```
DDD_FORUM_IS_PRODUCTION=false
DDD_FORUM_APP_SECRET=defaultappsecret
DDD_FORUM_REDIS_URL=
DDD_FORUM_REDIS_PORT=
DDD_FORUM_DB_USER=chun
DDD_FORUM_DB_PASS=12345678
DDD_FORUM_DB_HOST=
DDD_FORUM_DB_DEV_DB_NAME=data_dev
DDD_FORUM_DB_TEST_DB_NAME=data_test
DDD_FORUM_DB_PROD_DB_NAME=data_prod
```

if I run `docker-compose up`, I get the following error in my terminal:

```
Starting ddd_forum_mysql ... done
Starting ddd_forum_redis ... done
Starting ddd-forum_adminer_1 ... done
Starting ddd_app             ... done
Attaching to ddd_forum_redis, ddd_forum_mysql, ddd-forum_adminer_1, ddd_app
ddd_forum_mysql | 2021-01-06 01:53:50+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
ddd_app    | Waitin for mysql to start...
ddd_forum_redis | 1:C 06 Jan 2021 01:53:50.722 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
ddd_forum_redis | 1:C 06 Jan 2021 01:53:50.723 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
ddd_forum_redis | 1:C 06 Jan 2021 01:53:50.723 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
ddd_forum_mysql | 2021-01-06 01:53:50+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
ddd_forum_mysql | 2021-01-06 01:53:50+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
ddd_forum_redis | 1:M 06 Jan 2021 01:53:50.724 * Running mode=standalone, port=6379.
ddd_forum_redis | 1:M 06 Jan 2021 01:53:50.724 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
ddd_forum_redis | 1:M 06 Jan 2021 01:53:50.724 # Server initialized
ddd_forum_redis | 1:M 06 Jan 2021 01:53:50.725 * Loading RDB produced by version 6.0.9
ddd_forum_redis | 1:M 06 Jan 2021 01:53:50.725 * RDB age 202 seconds
ddd_forum_redis | 1:M 06 Jan 2021 01:53:50.725 * RDB memory usage when created 0.76 Mb
ddd_forum_redis | 1:M 06 Jan 2021 01:53:50.725 * DB loaded from disk: 0.000 seconds
ddd_forum_redis | 1:M 06 Jan 2021 01:53:50.725 * Ready to accept connections
adminer_1  | [Wed Jan  6 01:53:51 2021] PHP 7.4.13 Development Server (http://[::]:8080) started
ddd_forum_mysql | 2021-01-06T01:53:51.196146Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.22) starting as process 1
ddd_forum_mysql | 2021-01-06T01:53:51.208664Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
ddd_forum_mysql | 2021-01-06T01:53:51.445568Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
ddd_forum_mysql | 2021-01-06T01:53:51.562691Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
ddd_forum_mysql | 2021-01-06T01:53:51.657957Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
ddd_forum_mysql | 2021-01-06T01:53:51.658195Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
ddd_forum_mysql | 2021-01-06T01:53:51.661323Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
ddd_forum_mysql | 2021-01-06T01:53:51.688163Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.22'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
ddd_app    | MySQL started
ddd_app    |
ddd_app    | > ddd-forum@1.0.0 db:create:dev /usr/src/ddd
ddd_app    | > cross-env NODE_ENV=development node scripts/db/create
ddd_app    |
ddd_app    | /usr/src/ddd/scripts/db/create.js:25
ddd_app    |   if (err) throw err;
ddd_app    |            ^
ddd_app    |
ddd_app    | Error: Access denied for user ''@'172.18.0.5' (using password: NO)
ddd_app    |     at Packet.asError (/usr/src/ddd/node_modules/mysql2/lib/packets/packet.js:708:17)
ddd_app    |     at ClientHandshake.execute (/usr/src/ddd/node_modules/mysql2/lib/commands/command.js:28:26)
ddd_app    |     at Connection.handlePacket (/usr/src/ddd/node_modules/mysql2/lib/connection.js:408:32)
ddd_app    |     at PacketParser.onPacket (/usr/src/ddd/node_modules/mysql2/lib/connection.js:70:12)
ddd_app    |     at PacketParser.executeStart (/usr/src/ddd/node_modules/mysql2/lib/packet_parser.js:75:16)
ddd_app    |     at Socket.<anonymous> (/usr/src/ddd/node_modules/mysql2/lib/connection.js:77:25)
ddd_app    |     at Socket.emit (events.js:315:20)
ddd_app    |     at addChunk (_stream_readable.js:295:12)
ddd_app    |     at readableAddChunk (_stream_readable.js:271:9)
ddd_app    |     at Socket.Readable.push (_stream_readable.js:212:10) {
ddd_app    |   code: 'ER_ACCESS_DENIED_ERROR',
ddd_app    |   errno: 1045,
ddd_app    |   sqlState: '28000',
ddd_app    |   sqlMessage: "Access denied for user ''@'172.18.0.5' (using password: NO)"
ddd_app    | }
ddd_app    | npm ERR! code ELIFECYCLE
ddd_app    | npm ERR! errno 1
ddd_app    | npm ERR! ddd-forum@1.0.0 db:create:dev: `cross-env NODE_ENV=development node scripts/db/create`
.
.
.
```

I get this error whether I set "DDD_FORUM_DB_HOST" to localhost or leave blank. I'm sure I'm probably not setting up the .env file correctly or something.

Would anyone have any idea why this might be happening?

**Comment by aashir-khan** [comment]
I also get this error if I use the .env.template exactly as my .env (i.e. copy paste without any changes)

**Comment by stemmlerjs** [comment]
Hey @aashir-khan, thanks for trying out ddd-forum! Looking into this right now.

**Comment by stemmlerjs** [comment]
@aashir-khan I just tested it out on both my Windows machine and Mac with fresh container instances and that seemed to work. Let's see. 

The line from that error message that's most striking to me is:

```
Error: Access denied for user ''@'172.18.0.5' (using password: NO)
```

That would imply that the `DDD_FORUM_DB_USER` (ie: the `user` variable) isn't being picked up. I wonder if _any_ of the variables are being picked up for you.

It looks what's missing is the `DDD_FORUM_DB_USER` variable in that `scripts/db/create.js` file.

```javascript
const mysql = require('mysql2');  

require('dotenv').config();

const { 
  DDD_FORUM_DB_USER, 
  DDD_FORUM_DB_PASS, 
  DDD_FORUM_DB_HOST,
  DDD_FORUM_DB_DEV_DB_NAME,
  DDD_FORUM_DB_TEST_DB_NAME,
  NODE_ENV
} = process.env;

const dbName = NODE_ENV === "development" 
  ? DDD_FORUM_DB_DEV_DB_NAME 
  : DDD_FORUM_DB_TEST_DB_NAME

const connection = mysql.createConnection({  
  host: DDD_FORUM_DB_HOST,  
  user: DDD_FORUM_DB_USER,  // <---- This is the user, and by default, it would be set to "chun"
  password: DDD_FORUM_DB_PASS  
});  

connection.connect((err) => {
  if (err) throw err;
  connection.query(`CREATE DATABASE ${dbName}`, (err, result) => {
    
    if (err && err.code === "ER_DB_CREATE_EXISTS") {
      console.log('Db already created');
      process.exit(0);
    } 
    
    if (err) {
      throw err;
    }

    console.log('Created db');
    process.exit(0);
  })
})
```

Here's something to try.

First, run: `docker image rm ddd-forum_web`

Then, in `docker-compose.yml`, add these two lines to the `environment` portion of the `web` service:

```
  web:
    container_name: ddd_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 5000:5000
    environment:
      - DDD_FORUM_APP_SECRET=${DDD_FORUM_APP_SECRET}
      - DDD_FORUM_REDIS_URL=ddd_forum_redis
      - DDD_FORUM_REDIS_PORT=6379
      - DDD_FORUM_DB_HOST=ddd_forum_mysql
      - DDD_FORUM_DB_USER=${DDD_FORUM_DB_USER}    # <--- Add this
      - DDD_FORUM_DB_PASS=${DDD_FORUM_DB_PASS}     # <--- Add this
      - DDD_FORUM_DB_DEV_DB_NAME=${DDD_FORUM_DB_DEV_DB_NAME}
    depends_on:
      - mysql
      - redis
```

Then restart with `docker-compose up`.

**Comment by aashir-khan** [comment]
Ahh yes that did the trick, I had to delete the containers before I was able to delete the image, after that things started working smoothly again:

![image](https://user-images.githubusercontent.com/25349581/103794753-1ca35900-5013-11eb-9475-8a656e55bce2.png)

Thank you very much! After I got it working, I decided to see if adding those two lines to `docker-compose.yml` was the issue here, and what I did was remove all the stopped containers and the ddd-forum_web image again, then removed the two added lines in `docker-compose.yml` and ran `docker-compose up` again and I didn't get the error this time and the app worked fine too. Quite weird

Anyway, this might have been an anomoly from my side and probably just an issue on my part that caused that error, please feel free to close this issue if you like
